version: "2"
services:
  web:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
